name: Build Devel Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Resolve Version
        run: |
          GIT_VER=$(git describe --tags --always 2>/dev/null || echo "devel")
          echo "Resolved Git Version: $GIT_VER"
          echo "GIT_VER=$GIT_VER" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push devel image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tathar26/v-ops:devel
          build-args: |
            APP_VERSION=${{ env.GIT_VER }}
          cache-from: type=registry,ref=tathar26/v-ops:buildcache
          cache-to: type=registry,ref=tathar26/v-ops:buildcache,mode=max

      - name: Trigger Portainer Webhook
        run: curl -X POST https://portainer.artmex-hosting.com/api/stacks/webhooks/bbbe346c-d742-427a-826b-a6f38be48401
